### PR TITLE
add check for urls that prevent incorrect urls

### LINKED ISSUE #172: Bug: Link view crashes when line break is included in text
**description** 
When adding a line break in the link tab, the QR code is created successfully. However, on retrieval the page crashes (internal server error),

### PR DESCRIPTION
**Pull request by JannikStreek**
closes #172

### CODE REVIEW

**Comment by nwittstruck** [comment]
Showing an error works, and we should definitely do this. We could also think about just removing trailing whitespaces, as this happens quite easily in the form. We could also change the form, so that the form gets submitted once a user presses enter, instead of adding a new line for links. What do you think?

**Comment by JannikStreek** [comment]
> Showing an error works, and we should definitely do this. We could also think about just removing trailing whitespaces, as this happens quite easily in the form. We could also change the form, so that the form gets submitted once a user presses enter, instead of adding a new line for links. What do you think?

You mean in addition? We can do that, but I would still try to resolve the link as otherwise it will still crash e.g. when there is a line break in the middle of the link...

**Comment by nwittstruck** [comment]
Yes, additionally. The check on the server side is great!

**Comment by nwittstruck** [comment]
See #186

**Pull request closed without merging**
